language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev:i386 gcc-multilib g++-multilib libusb-1.0-0-dev udev

install: "pip install trezor"

before_script: "make build_unix"

script: "cd src/tests && bash ./runtests.sh"
