language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get install libsdl2-dev gcc-multilib g++-multilib
  - make build_unix

install: "pip install trezor"

script: "cd src/tests && bash ./runtests.sh"
